ImageTransf.class: resources/Picture.class resources/In.class resources/StdOut.class ImageTransf.java
	javac ImageTransf.java

resources/Picture.class: resources/Picture.java 
	javac Picture.java

resources/In.class: resources/In.java 
	Javac In.java

resources/StdOut.class: resources/StdOut.java 
	Javac StdOut.java
	
clean: 
	rm *.class